"""add_sales_customers_payments

Revision ID: 1c522df3ddb1
Revises: 25c28a942ae4
Create Date: 2026-03-28 19:06:56.591589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c522df3ddb1'
down_revision: Union[str, None] = '25c28a942ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
