"""add_sales_payments_customers

Revision ID: 8a188368a1ca
Revises: c5fb7cc66e47
Create Date: 2026-03-28 18:59:20.210807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a188368a1ca'
down_revision: Union[str, None] = 'c5fb7cc66e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('customers', 'gstin')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.add_column('sales_invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('sales_invoices', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales_invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('sales_invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
    op.alter_column('sales_invoices', 'payment_status',
               existing_type=postgresql.ENUM('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE', name='paymentstatus'),
               nullable=True)
    op.alter_column('sales_invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sales_invoices', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sales_invoices', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_sales_invoices_invoice_number', table_name='sales_invoices')
    op.create_unique_constraint(op.f('uq_sales_invoices_invoice_number'), 'sales_invoices', ['invoice_number'])
    op.drop_column('sales_invoices', 'tax_amount')
    op.drop_column('sales_invoices', 'updated_at')
    op.drop_column('sales_invoices', 'subtotal')
    op.add_column('sales_line_items', sa.Column('description', sa.String(), nullable=False))
    op.alter_column('sales_line_items', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales_line_items', 'line_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('sales_line_items', 'updated_at')
    op.drop_column('sales_line_items', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_line_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('sales_line_items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('sales_line_items', 'line_total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sales_line_items', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sales_line_items', 'description')
    op.add_column('sales_invoices', sa.Column('subtotal', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('sales_invoices', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('sales_invoices', sa.Column('tax_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_sales_invoices_invoice_number'), 'sales_invoices', type_='unique')
    op.create_index('ix_sales_invoices_invoice_number', 'sales_invoices', ['invoice_number'], unique=True)
    op.alter_column('sales_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sales_invoices', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales_invoices', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('sales_invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('sales_invoices', 'payment_status',
               existing_type=postgresql.ENUM('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE', name='paymentstatus'),
               nullable=False)
    op.alter_column('sales_invoices', 'amount_paid',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('sales_invoices', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('sales_invoices', 'customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('sales_invoices', 'notes')
    op.add_column('customers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('customers', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('customers', 'credit_limit')
    op.drop_column('customers', 'contact_name')
    # ### end Alembic commands ###
