"""add_payment_terms_to_suppliers

Revision ID: dc1ceee91c0a
Revises: 1c522df3ddb1
Create Date: 2026-03-28 19:56:24.305649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc1ceee91c0a'
down_revision: Union[str, None] = '1c522df3ddb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('sales_invoice_id', sa.String(), nullable=False))
    op.add_column('payments', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('recorded_by', sa.String(), nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('fk_payments_invoice_id_sales_invoices', 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_sales_invoice_id_sales_invoices'), 'payments', 'sales_invoices', ['sales_invoice_id'], ['id'])
    op.create_foreign_key(op.f('fk_payments_recorded_by_users'), 'payments', 'users', ['recorded_by'], ['id'])
    op.drop_column('payments', 'invoice_id')
    op.drop_column('payments', 'updated_at')
    op.add_column('suppliers', sa.Column('payment_terms', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'payment_terms')
    op.add_column('payments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('invoice_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_payments_recorded_by_users'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_sales_invoice_id_sales_invoices'), 'payments', type_='foreignkey')
    op.create_foreign_key('fk_payments_invoice_id_sales_invoices', 'payments', 'sales_invoices', ['invoice_id'], ['id'])
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.drop_column('payments', 'recorded_by')
    op.drop_column('payments', 'notes')
    op.drop_column('payments', 'sales_invoice_id')
    # ### end Alembic commands ###
